#ifndef WAMP_H
#define WAMP_H

enum e_message_codes {
    WAMP_MSGCODE_HELLO        = 1,
    WAMP_MSGCODE_WELCOME      = 2,
    WAMP_MSGCODE_ABORT        = 3,
    WAMP_MSGCODE_GOODBYE      = 6,

    WAMP_MSGCODE_ERROR        = 8,

    WAMP_MSGCODE_PUBLISH      = 16,
    WAMP_MSGCODE_PUBLISHED    = 17,

    WAMP_MSGCODE_SUBSCRIBE    = 32,
    WAMP_MSGCODE_SUBSCRIBED   = 33,
    WAMP_MSGCODE_UNSUBSCRIBE  = 34,
    WAMP_MSGCODE_UNSUBSCRIBED = 35,
    WAMP_MSGCODE_EVENT        = 36,

    WAMP_MSGCODE_CALL         = 48,
    WAMP_MSGCODE_RESULT       = 50,

    WAMP_MSGCODE_REGISTER     = 64,
    WAMP_MSGCODE_REGISTERED   = 65,
    WAMP_MSGCODE_UNREGISTER   = 66,
    WAMP_MSGCODE_UNREGISTERED = 67,
    WAMP_MSGCODE_INVOCATION   = 68,
    WAMP_MSGCODE_YIELD        = 70
};

#endif
